language: node_js
node_js:
  - "9.6.1"
cache:
  directories:
    - node_modules
script:
  - npm test
env:
  - CI=true
before_deploy:
 - npm install netlify-cli -g
 - npm run build

deploy:
 provider: script
 script: netlify deploy -p ./build
 skip_cleanup: true
 on:
   branch: master